### ISSUE TITLE
Issue with Internet Explorer

### ISSUE THREAD

**Issue by manolo20** [uRosConf/voronoiTreemap#1]
Voronoi plot does not work in IE. Although, it works perfectly in Chrome and Mozilla Firefox.

**Comment by alexcipro** [comment]
What is IE?:)))
Thanks,Cip


 

    On Tuesday, October 9, 2018, 3:40:37 AM GMT+3, Manolo <notifications@github.com> wrote:  
 
 
Voronoi plot does not work in IE. Although, it works perfectly in Chrome and Mozilla Firefox.

**Comment by alexkowa** [comment]
Did you take a look at the d3-voronoi-treemap demos if they work? there is also version 2.0 out since last week, so maybe it is fixed there?!

**Comment by manolo20** [comment]
IE = internet explorer. Good call Alex, I will double check version 2.0 and update the issue.
