### ISSUE TITLE
Issue with datatable buttons

### ISSUE THREAD

**Issue by gd047** [uRosConf/voronoiTreemap#4]
https://rstudio.github.io/DT/extensions.html

I have put a voronoiTreemap before a DT control with buttons enabled, in an Rmd file. I noticed that the "weight" data from voronoid always appear as the first line of any DT button output file.

**Comment by alexkowa** [comment]
Thank you that should not happen. Can you share a dummy Rmd file, where this happens?

**Comment by gd047** [comment]
I guess this will do.
[cash_flow_total.zip](https://github.com/uRosConf/voronoiTreemap/files/2914724/cash_flow_total.zip)

**Comment by alexkowa** [comment]
[rstudio-export (2).zip](https://github.com/uRosConf/voronoiTreemap/files/2914825/rstudio-export.2.zip)

I simplyfied it even further, but I don't see the problem you are describing.
Maybe it is just something related to the html code in between (which I removed)

**Comment by gd047** [comment]
I still see the problem in your file. I attach images from the excel and pdf DT outputs. The highlighted text comes from the "weight" column used in voronoid.
![image](https://user-images.githubusercontent.com/3167917/53565706-d18ca500-3b62-11e9-8cc0-231c8f0b0235.png)
![image](https://user-images.githubusercontent.com/3167917/53565864-4eb81a00-3b63-11e9-9618-76af3d3caf26.png)

**Comment by alexkowa** [comment]
Ah, now I at least understand what you mean, only in the export the additional information appears. 
However, I am afraid I cannot help you here, the JSON with the information for the voronoiTreemap looks fine and is validated positively.
